export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"

export const SET_FILTRE = "SET_FILTRE"
export const UPDATE_PALETTE_LIKE = "UPDATE_PALETTE_LIKE"

export const FETCH_PALETTES_START = "FETCH_PALETTES_START"
export const FETCH_PALETTES_SUCCESS = "FETCH_PALETTES_SUCCESS"
export const FETCH_PALETTES_FAIL = "FETCH_PALETTES_FAIL"

export const GET_USER_LIKES_FAIL = "GET_USER_LIKES_FAIL"
export const GET_USER_LIKES_SUCCESS = "GET_USER_LIKES_SUCCESS"

export const POST_LIKE_START = "POST_LIKE_START"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POST_LIKE_FAIL = "POST_LIKE_FAIL"

export const SET_USER_LIKE_START = "SET_USER_LIKE_START"
export const SET_USER_LIKE_SUCCESS = "SET_USER_LIKE_SUCCESS"
export const SET_USER_LIKE_FAIL = "SET_USER_LIKE_FAIL"

export const SET_USER_DISLIKE_START = "SET_USER_DISLIKE_START"

export const POST_PALETTE_INIT = "POST_PALETTE_INIT"
export const POST_PALETTE_START = "POST_PALETTE_START"
export const POST_PALETTE_SUCCESS = "POST_PALETTE_SUCCESS"
export const POST_PALETTE_FAIL = "POST_PALETTE_FAIL"
